export const photoMap: Record<string, string> = {
  "afthah": "/photo/AFTHAH.png",
  "afhah": "/photo/AFTHAH.png",
  "adil pk": "/photo/Adil pk.png",
  "asnaf": "/photo/Asnaf.png",
  "basith": "/photo/Basith.png",
  "farhan m": "/photo/Farhan M.png",
  "farhan": "/photo/Farhan.png",
  "fayiz": "/photo/Fayiz.png",
  "midlaj": "/photo/MIDLAJ.png",
  "misab": "/photo/Misab.png",
  "muhammed g": "/photo/Muhammed G.png",
  "nabhan": "/photo/Nabhan.png",
  "najih": "/photo/Najih.png",
  "rizwan": "/photo/Rizwan.jpg",
  "sahad": "/photo/Sahad.png",
  "shabeeb": "/photo/Shabeeb.png",
  "thansif": "/photo/THANSIF.png",
  "arafath": "/photo/arafath.png",
  "irshad": "/photo/irshad.png",
  "jaseem": "/photo/jaseem.png",
  "muhd p": "/photo/muhd p.png",
  "muhammed p": "/photo/muhd p.png",
  "muhsin": "/photo/muhsin.png",
  "munavvir": "/photo/munavvir.png",
  "munna": "/photo/munna.png",
  "munawir": "/photo/munna.png",
  "munzir": "/photo/munzir.png",
  "najash": "/photo/najash.png",
  "nasru": "/photo/nasru.png",
  "nasrullah": "/photo/nasru.png",
  "ramees": "/photo/ramees.png",
  "saad": "/photo/saad.png",
  "sabeer": "/photo/sabeer.png",
  "shabeer": "/photo/sabeer.png",
  "sayyid ameen": "/photo/sayyid ameen.png",
  "ameen thangal": "/photo/sayyid ameen.png",
  "shahid om": "/photo/shahid om.png",
  "shammas": "/photo/shammas.png",
  "shibili": "/photo/shibili.png",
  "shibli": "/photo/Shibli.png",
  "sinan al ameen": "/photo/sinan al ameen.png",
  "sinan cp": "/photo/sinan cp.png"
};